package webimage

import "testing"

func TestDedupeFileRefsKeepsOrder(t *testing.T) {
	got := dedupeFileRefs([]string{"a", "", "sed:b", "a", "sed:b", "c"})
	want := []string{"a", "sed:b", "c"}
	if len(got) != len(want) {
		t.Fatalf("len=%d want %d (%v)", len(got), len(want), got)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Fatalf("got[%d]=%q want %q (all=%v)", i, got[i], want[i], got)
		}
	}
}

func TestReferenceImageHashSetMatchesExactOriginal(t *testing.T) {
	refs := []ReferenceImage{{Data: []byte("original image bytes"), FileName: "input.png"}}
	hashes := referenceImageHashSet(refs)
	if !isReferenceImageBytes([]byte("original image bytes"), hashes) {
		t.Fatal("expected exact original bytes to be recognized as reference image")
	}
	if isReferenceImageBytes([]byte("generated image bytes"), hashes) {
		t.Fatal("generated bytes should not be recognized as reference image")
	}
}
